- name: My first play
  hosts: myhosts
  become: true
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Set authorized key taken from file
     ansible.posix.authorized_key:
       user: andy
       state: present
       key: "{{ lookup('file', '/home/andy/.ssh/id_ed25519.pub') }}"

   - name: Update all packages to their latest version
     ansible.builtin.apt:
       name: "*"
       state: latest

   - name: install qemu guest agent
     ansible.builtin.apt:
       name: qemu-guest-agent
       state: present

   - name: enable qemu guest agent
     ansible.builtin.systemd_service:
       name: qemu-guest-agent
       enabled: true

   - name: restart qemu guest agent
     ansible.builtin.systemd_service:
       name: qemu-guest-agent
       state: restarted

   - name: Extend the logical volume of ubuntu-lv
     community.general.lvol:
      vg: ubuntu-vg
      lv: ubuntu-lv
      size: +100%FREE

   - name: Extend Filesystem of ubuntu--vg-ubuntu--lv
     community.general.filesystem:
      dev: /dev/mapper/ubuntu--vg-ubuntu--lv
      fstype: ext4
      resizefs: true